'use client'

import {useEffect,useState} from 'react'
import {ArrowRight,BarChart3,Bell,BriefcaseBusiness,CalendarClock,Check,ChevronDown,ChevronRight,Clock3,Download,Headphones,LayoutDashboard,MapPin,Menu,Mic2,MoreHorizontal,Phone,PhoneCall,Play,Search,Settings,ShieldCheck,Sparkles,Upload,Users,UserSearch,X,Zap} from 'lucide-react'
import {api} from './api'
import type {Call,Candidate} from './types'
import {Badge} from '@/components/ui/badge'
import {Button} from '@/components/ui/button'

const FALLBACK:Candidate[]=[
 {id:'c1',name:'Aarav Mehta',role:'Senior Product Designer',company:'Razorpay',location:'Bengaluru, India',experience:7,match:96,phone:'+91 ••••• 0101',email:'aarav@example.com',skills:['Figma','Design systems','Research'],status:'Qualified',avatar:'AM'},
 {id:'c2',name:'Meera Nair',role:'Product Designer II',company:'CRED',location:'Bengaluru, India',experience:5,match:93,phone:'+91 ••••• 0102',email:'meera@example.com',skills:['Figma','Prototyping','Fintech'],status:'Interested',avatar:'MN'},
 {id:'c3',name:'Kabir Shah',role:'Senior UX Designer',company:'Groww',location:'Mumbai, India',experience:6,match:89,phone:'+91 ••••• 0103',email:'kabir@example.com',skills:['UX strategy','Research','Mobile'],status:'New',avatar:'KS'},
 {id:'c4',name:'Ishita Rao',role:'Product Designer',company:'Swiggy',location:'Hyderabad, India',experience:4,match:86,phone:'+91 ••••• 0104',email:'ishita@example.com',skills:['Interaction','Figma','B2C'],status:'Call scheduled',avatar:'IR'},
]

type Page='Overview'|'People search'|'Outreach'|'Conversations'|'Attendance plan'
const nav:[Page,typeof LayoutDashboard][]=[['Overview',LayoutDashboard],['People search',UserSearch],['Outreach',PhoneCall],['Conversations',Headphones],['Attendance plan',ShieldCheck]]
const defaultJD=`We are looking for a Senior Product Designer to join our product team in Bengaluru. You will own end-to-end design for fintech experiences, conduct user research, create high-fidelity prototypes in Figma, and evolve our design system.\n\nRequirements: 5+ years of product design experience, strong portfolio, excellent communication, and experience collaborating with product and engineering teams.`

function Logo(){return <div className="logo"><span><Zap size={17} fill="currentColor"/></span>reachly</div>}
function Pill({children,tone='gray'}:{children:React.ReactNode;tone?:string}){return <Badge className={tone}>{children}</Badge>}

export default function App(){
 const [page,setPage]=useState<Page>('Overview'),[mobileNav,setMobileNav]=useState(false),[candidates,setCandidates]=useState<Candidate[]>(FALLBACK),[calls,setCalls]=useState<Call[]>([]),[selected,setSelected]=useState<string[]>(['c1','c2','c3']),[toast,setToast]=useState(''),[live,setLive]=useState(false)
 const refreshCalls=()=>api.calls().then(x=>setCalls(x.results)).catch(()=>{})
 useEffect(()=>{api.candidates().then(x=>setCandidates(x.results)).catch(()=>{});refreshCalls();api.health().then(x=>setLive(x.hunar_configured&&x.live_calls)).catch(()=>{})},[])
 const show=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),3200)}
 return <div className="app">
  <aside className={mobileNav?'open':''}><div className="brand-row"><Logo/><button className="icon mobile-only" onClick={()=>setMobileNav(false)}><X size={19}/></button></div><div className="workspace"><div className="workspace-icon">AC</div><div><b>Acme India</b><small>Talent team</small></div><ChevronDown size={16}/></div><nav>{nav.map(([label,Icon])=><button key={label} className={page===label?'active':''} onClick={()=>{setPage(label);setMobileNav(false)}}><Icon size={18}/>{label}{label==='Conversations'&&<em>3</em>}</button>)}</nav><div className="side-bottom"><div className="trial"><div><Sparkles size={17}/><b>7 days left</b></div><p>Explore unlimited searches and voice outreach.</p><button>View plan <ArrowRight size={14}/></button></div><button className="profile"><span>DK</span><div><b>Divya Kumari</b><small>Administrator</small></div><MoreHorizontal size={18}/></button></div></aside>
  {mobileNav&&<div className="scrim" onClick={()=>setMobileNav(false)}/>}<main><header><button className="icon mobile-only" onClick={()=>setMobileNav(true)}><Menu/></button><div className="crumb">Acme India <ChevronRight size={14}/> <b>{page}</b></div><div className="header-actions"><div className={`connection ${live?'live':''}`}><i/> {live?'Hunar live':'Safe demo mode'}</div><button className="icon"><Search size={18}/></button><button className="icon"><Bell size={18}/><i className="notification"/></button></div></header>
  {page==='Overview'&&<Overview candidates={candidates} calls={calls} go={setPage}/>} {page==='People search'&&<PeopleSearch candidates={candidates} setCandidates={setCandidates} selected={selected} setSelected={setSelected} go={setPage} show={show}/>} {page==='Outreach'&&<Outreach candidates={candidates.filter(c=>selected.includes(c.id))} show={show} go={setPage} refreshCalls={refreshCalls}/>} {page==='Conversations'&&<Conversations calls={calls}/>} {page==='Attendance plan'&&<Attendance/>}
  </main>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}

function Overview({candidates,calls,go}:{candidates:Candidate[];calls:Call[];go:(p:Page)=>void}){
 const complete=calls.filter(c=>c.status==='COMPLETED').length
 return <div className="page"><div className="welcome"><div><Pill tone="lime"><Sparkles size={13}/> AI hiring workspace</Pill><h1>Good afternoon, Divya.</h1><p>Here’s what’s happening across your hiring pipeline today.</p></div><Button onClick={()=>go('People search')}><UserSearch size={17}/> Find candidates</Button></div>
 <section className="metrics"><article><span className="metric-icon purple"><Users/></span><div><small>Candidates found</small><strong>{candidates.length*21}</strong><p><b>+18%</b> this week</p></div></article><article><span className="metric-icon green"><PhoneCall/></span><div><small>Calls completed</small><strong>{complete+41}</strong><p><b>82%</b> connect rate</p></div></article><article><span className="metric-icon orange"><Sparkles/></span><div><small>Interested</small><strong>18</strong><p><b>42%</b> of connected</p></div></article><article><span className="metric-icon blue"><CalendarClock/></span><div><small>Interviews booked</small><strong>7</strong><p><b>+3</b> since Monday</p></div></article></section>
 <div className="overview-grid"><section className="card activity"><div className="card-head"><div><h2>Hiring activity</h2><p>Candidate engagement over the last 7 days</p></div><select><option>Last 7 days</option></select></div><div className="chart"><div className="y-axis"><span>60</span><span>40</span><span>20</span><span>0</span></div><div className="bars">{[35,46,40,61,54,75,67].map((v,i)=><div className="bar-col" key={i}><div className="bar-bg"><i style={{height:`${v}%`}}/><b style={{height:`${Math.max(16,v-27)}%`}}/></div><span>{['Fri','Sat','Sun','Mon','Tue','Wed','Thu'][i]}</span></div>)}</div></div><div className="legend"><span><i className="dot purple-bg"/>Candidates found</span><span><i className="dot lime-bg"/>Connected</span></div></section>
 <section className="card next"><div className="card-head"><div><h2>Up next</h2><p>Scheduled interviews</p></div><button className="link">View calendar</button></div>{[['AM','Aarav Mehta','Senior Product Designer','Today · 4:30 PM'],['MN','Meera Nair','Product Designer II','Tomorrow · 11:00 AM'],['KS','Kabir Shah','Senior UX Designer','Sep 06 · 2:00 PM']].map((x,i)=><div className="interview" key={x[1]}><span className={`avatar a${i}`}>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small><p><Clock3 size={13}/>{x[3]}</p></div><button className="icon"><MoreHorizontal/></button></div>)}</section></div>
 <section className="card recent"><div className="card-head"><div><h2>Recent conversations</h2><p>Latest candidate outreach powered by Hunar Voice AI</p></div><button className="secondary" onClick={()=>go('Conversations')}>View all <ArrowRight size={15}/></button></div><ConversationTable calls={calls}/></section></div>
}

function PeopleSearch({candidates,setCandidates,selected,setSelected,go,show}:{candidates:Candidate[];setCandidates:(v:Candidate[])=>void;selected:string[];setSelected:(v:string[])=>void;go:(p:Page)=>void;show:(m:string)=>void}){
 const [jd,setJd]=useState(defaultJD),[location,setLocation]=useState('India'),[loading,setLoading]=useState(false),[searched,setSearched]=useState(false)
 const run=async()=>{setLoading(true);try{const r=await api.search(jd,location);setCandidates(r.results);setSelected(r.results.slice(0,3).map(candidate=>candidate.id));setSearched(true);show(`${r.total} strong matches found`)}catch{setSearched(true);show('Showing demo matches — backend is offline')}finally{setLoading(false)}}
 const toggle=(id:string)=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id])
 return <div className="page search-page"><div className="title-row"><div><span className="eyebrow">PEOPLE SEARCH</span><h1>Find your next great hire.</h1><p>Paste a job description. We’ll understand the role and surface the best-fit people.</p></div><button className="secondary"><Upload size={16}/> Import CSV</button></div>
 <section className="search-builder card"><div className="builder-head"><div className="step">1</div><div><h2>Tell us who you’re looking for</h2><p>We’ll extract skills, seniority, location, and experience automatically.</p></div><Pill tone="lime"><Sparkles size={13}/> AI-powered</Pill></div><label>Job description<textarea value={jd} onChange={e=>setJd(e.target.value)} /><span>{jd.length.toLocaleString()} / 12,000</span></label><div className="filters"><label><span>Location</span><div className="input"><MapPin size={16}/><input value={location} onChange={e=>setLocation(e.target.value)}/></div></label><label><span>Experience</span><select><option>3 – 12 years</option></select></label><label><span>Company type</span><select><option>Any company</option><option>Startup</option><option>Enterprise</option></select></label><button className="primary search-btn" disabled={loading||jd.length<20} onClick={run}>{loading?<i className="spinner"/>:<Search size={17}/>} {loading?'Finding people…':'Find matching people'}</button></div></section>
 {(searched||candidates.length>0)&&<section className="results"><div className="results-head"><div><h2>{candidates.length} people match this role</h2><p>Ranked by experience, skills, and role relevance</p></div><div><button className="secondary"><Download size={15}/> Export</button><button className="primary" disabled={!selected.length} onClick={()=>go('Outreach')}><PhoneCall size={16}/> Reach out to {selected.length}</button></div></div><div className="candidate-list">{candidates.map(c=><article className={`candidate card ${selected.includes(c.id)?'selected':''}`} key={c.id}><button className={`check ${selected.includes(c.id)?'checked':''}`} onClick={()=>toggle(c.id)}>{selected.includes(c.id)&&<Check size={14}/>}</button><span className="avatar large">{c.avatar}</span><div className="candidate-main"><div><h3>{c.name}</h3><Pill tone={c.status==='Qualified'||c.status==='Interested'?'green':'gray'}>{c.status}</Pill></div><b>{c.role} <span>at {c.company}</span></b><p><MapPin size={14}/>{c.location}<i/> {c.experience} years experience</p><div className="skills">{c.skills.map(s=><Pill key={s}>{s}</Pill>)}</div></div><div className="match"><strong>{c.match}%</strong><span>match</span><div><i style={{width:`${c.match}%`}}/></div></div><button className="icon"><MoreHorizontal/></button></article>)}</div></section>}</div>
}

function Outreach({candidates,show,go,refreshCalls}:{candidates:Candidate[];show:(m:string)=>void;go:(p:Page)=>void;refreshCalls:()=>Promise<void>}){
 const [channel,setChannel]=useState<'voice'|'voice+sms'>('voice'),[launching,setLaunching]=useState(false),[script,setScript]=useState('Hi {{first_name}}, I’m Maya, an AI hiring assistant calling on behalf of Acme. I came across your profile and thought your experience could be a strong match for our Senior Product Designer role. Is now a good time for a quick conversation?')
 const launch=async()=>{if(!candidates.length)return;setLaunching(true);try{const r=await api.outreach(candidates.map(c=>c.id),channel);await refreshCalls();show(`${r.message} · ${r.mode} mode`);setTimeout(()=>go('Conversations'),900)}catch(e){show(e instanceof Error?e.message:'Could not launch outreach')}finally{setLaunching(false)}}
 return <div className="page"><div className="title-row"><div><span className="eyebrow">VOICE OUTREACH</span><h1>Start a thoughtful conversation.</h1><p>Configure your AI agent, review the shortlist, and let Hunar handle every call.</p></div><Pill tone="lime"><Mic2 size={14}/> Powered by Hunar AI</Pill></div><div className="outreach-grid"><div><section className="card setup"><div className="builder-head"><div className="step">1</div><div><h2>Choose a channel</h2><p>Voice-first outreach with an optional follow-up.</p></div></div><div className="channel-grid"><button className={channel==='voice'?'selected':''} onClick={()=>setChannel('voice')}><span><PhoneCall/></span><b>Voice call</b><small>Natural AI conversation</small><Check/></button><button className={channel==='voice+sms'?'selected':''} onClick={()=>setChannel('voice+sms')}><span><Zap/></span><b>Voice + SMS</b><small>Text follow-up after call</small><Check/></button></div></section><section className="card setup"><div className="builder-head"><div className="step">2</div><div><h2>Conversation brief</h2><p>Give Maya context; she’ll adapt naturally.</p></div></div><label>Opening message<textarea value={script} onChange={e=>setScript(e.target.value)}/></label><div className="questions"><b>Screening questions</b>{['Are you open to exploring a new opportunity?','What is your current notice period?','What are your current and expected compensation?','When are you available for an interview?'].map((q,i)=><div><span>{i+1}</span>{q}<MoreHorizontal size={16}/></div>)}</div></section></div><aside className="card launch-card"><div className="agent"><span><Mic2/></span><div><small>YOUR AI AGENT</small><h3>Maya</h3><p>Warm · Professional · English + Hindi</p></div><i className="online"/></div><hr/><h3>Campaign summary</h3><div className="summary-row"><span>Candidates</span><b>{candidates.length}</b></div><div className="summary-row"><span>Channel</span><b>{channel==='voice'?'Voice call':'Voice + SMS'}</b></div><div className="summary-row"><span>Expected duration</span><b>3–5 min each</b></div><div className="mini-list">{candidates.slice(0,4).map(c=><div><span className="avatar small">{c.avatar}</span><div><b>{c.name}</b><small>{c.role}</small></div><Check size={15}/></div>)}{candidates.length>4&&<p>+{candidates.length-4} more candidates</p>}</div><button className="primary full" disabled={!candidates.length||launching} onClick={launch}>{launching?<i className="spinner"/>:<Play size={16} fill="currentColor"/>}{launching?'Launching…':`Launch ${candidates.length} calls`}</button><p className="secure"><ShieldCheck size={14}/> Calls are recorded only with candidate consent.</p></aside></div></div>
}

function Conversations({calls}:{calls:Call[]}){const [active,setActive]=useState<Call|undefined>(calls[0]);useEffect(()=>{if(!active&&calls[0])setActive(calls[0])},[calls]);return <div className="page"><div className="title-row"><div><span className="eyebrow">CONVERSATIONS</span><h1>Every answer, ready to act on.</h1><p>Review call outcomes, transcripts, and structured candidate insights.</p></div><button className="secondary"><Download size={16}/> Export responses</button></div><div className="conversation-layout"><section className="card conversation-list"><div className="list-search"><Search/><input placeholder="Search candidates…"/></div>{calls.map(c=><button className={active?.id===c.id?'active':''} onClick={()=>setActive(c)}><span className="avatar">{c.candidate_name.split(' ').map(x=>x[0]).join('')}</span><div><b>{c.candidate_name}</b><small>{c.status.replace('_',' ').toLowerCase()}</small><p>{c.transcript?.at(-1)?.text||'No conversation captured yet'}</p></div><time>{c.duration?`${Math.floor(c.duration/60)}:${String(c.duration%60).padStart(2,'0')}`:'—'}</time></button>)}</section><section className="card detail">{active?<><div className="detail-head"><span className="avatar large">{active.candidate_name.split(' ').map(x=>x[0]).join('')}</span><div><h2>{active.candidate_name}</h2><p><Pill tone={active.status==='COMPLETED'?'green':'gray'}>{active.status.replace('_',' ')}</Pill> {active.duration?`${Math.floor(active.duration/60)} min ${active.duration%60} sec`:'No duration'}</p></div><button className="secondary"><Phone size={15}/> Call again</button></div>{active.status==='COMPLETED'?<><h3>Screening summary</h3><div className="answer-grid">{Object.entries(active.result).map(([k,v])=><div><small>{k.replaceAll('_',' ')}</small><b>{v}</b></div>)}</div><div className="transcript-head"><h3>Transcript</h3><button className="link"><Play size={14}/> Play recording</button></div><div className="transcript">{active.transcript.map(t=><div className={t.speaker==='AI'?'ai':''}><b>{t.speaker==='AI'?'Maya · AI agent':active.candidate_name}</b><p>{t.text}</p></div>)}</div></>:<div className="empty"><PhoneCall/><h3>Candidate was not connected</h3><p>The retry policy will automatically try again during the candidate’s preferred calling hours.</p></div>}</>:<div className="empty"><Headphones/><h3>No conversations yet</h3><p>Launch an outreach campaign to see structured answers here.</p></div>}</section></div></div>}

function ConversationTable({calls}:{calls:Call[]}){return <div className="table"><div className="tr th"><span>Candidate</span><span>Outcome</span><span>Key response</span><span>Duration</span><span/></div>{calls.slice(0,4).map(c=><div className="tr"><span className="person"><i className="avatar small">{c.candidate_name.split(' ').map(x=>x[0]).join('')}</i><b>{c.candidate_name}</b></span><span><Pill tone={c.status==='COMPLETED'?'green':'gray'}>{c.status.replace('_',' ')}</Pill></span><span>{c.result?.interest?`${c.result.interest} interest · ${c.result.notice_period}`:'Retry scheduled'}</span><span>{c.duration?`${Math.floor(c.duration/60)}m ${c.duration%60}s`:'—'}</span><button className="icon"><ChevronRight/></button></div>)}</div>}

function Attendance(){const steps=[['01','Local IVR check-in','Every location gets a dedicated phone number. Employees call from any feature phone or shared landline and enter their employee PIN.'],['02','Voice biometric + location proof','The AI asks a rotating spoken phrase, matches the enrolled voiceprint, and verifies the originating site number or supervisor kiosk.'],['03','Offline-first site gateway','A low-cost GSM/landline terminal stores encrypted events during outages and syncs them centrally when connectivity returns.'],['04','Exception-only HR workflow','LLM flags duplicate, late, missing, or suspicious entries and calls the employee or supervisor for clarification automatically.']];return <div className="page attendance"><div className="attendance-hero"><Pill tone="lime"><ShieldCheck size={13}/> Assignment challenge 03</Pill><h1>Attendance without apps.<br/><em>Built for the real world.</em></h1><p>A voice-first, privacy-aware attendance system for 1,000 employees across 100 locations—using feature phones, landlines, and an LLM coordination layer.</p><div><Pill>1,000 employees</Pill><Pill>100 locations</Pill><Pill>No smartphones</Pill><Pill>Works offline</Pill></div></div><section className="architecture card"><div className="card-head"><div><span className="eyebrow">SYSTEM DESIGN</span><h2>One simple action for employees.<br/>Complete visibility for HR.</h2></div></div><div className="flow"><div><span><Phone/></span><b>Employee</b><small>Feature phone / landline</small></div><ArrowRight/><div><span><Mic2/></span><b>Voice IVR</b><small>PIN + voice phrase</small></div><ArrowRight/><div><span><ShieldCheck/></span><b>Verification</b><small>Identity + site proof</small></div><ArrowRight/><div><span><Sparkles/></span><b>LLM layer</b><small>Exceptions + follow-ups</small></div><ArrowRight/><div><span><BarChart3/></span><b>HR dashboard</b><small>Live attendance view</small></div></div></section><section className="plan-grid">{steps.map(([n,t,d])=><article className="card"><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</section><section className="guardrails"><div><ShieldCheck/><h2>Designed against buddy punching</h2><p>Voiceprint liveness, one-time rotating phrases, site-bound caller IDs, anomaly scoring, and supervisor verification protect accuracy without turning attendance into surveillance.</p></div><div><Clock3/><h2>Graceful when systems fail</h2><p>Each site has paper fallback codes generated daily. Supervisors SMS or call in the batch once lines recover; every correction remains visible in an immutable audit trail.</p></div><div><Users/><h2>Human review stays in control</h2><p>The LLM never changes payroll data on its own. It gathers context, assigns confidence, and routes exceptions to HR with the call evidence and a recommended action.</p></div></section></div>}
